### Create user
POST http://localhost:1234/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "mia1",
  "email": "fghjk@mail.ru",
  "password": "123456"
}

### Log in
POST http://localhost:1234/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "fghjk@mail.ru",
  "password": "123456"
}

### Get user state
GET http://localhost:1234/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzOGUyMTk0YzU0NTQwYmJiYWVkMmEzNiIsImVtYWlsIjoiZmdoamtAbWFpbC5ydSIsImlhdCI6MTY3MDM5NzY3OCwiZXhwIjoxNjcwNTcwNDc4fQ.J1hLxWoIYxY99II_mT83Sey_5rDqS_h_casxZG8FlF0

### Create avatar
POST http://localhost:1234/users/638de5d64ff2cb3128ba0f0c/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/poluyanenko/Desktop/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get inList
GET http://localhost:1234/users/inList HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzOGUyMTk0YzU0NTQwYmJiYWVkMmEzNiIsImVtYWlsIjoiZmdoamtAbWFpbC5ydSIsImlhdCI6MTY3MDM5NzY3OCwiZXhwIjoxNjcwNTcwNDc4fQ.J1hLxWoIYxY99II_mT83Sey_5rDqS_h_casxZG8FlF0

### Add inList
POST http://localhost:1234/users/inList HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzOGUyMTk0YzU0NTQwYmJiYWVkMmEzNiIsImVtYWlsIjoiZmdoamtAbWFpbC5ydSIsImlhdCI6MTY3MDM5NzY3OCwiZXhwIjoxNjcwNTcwNDc4fQ.J1hLxWoIYxY99II_mT83Sey_5rDqS_h_casxZG8FlF0
Content-Type: application/json

{
  "movieId": "638bf2dd1fcdd20e4ec96b7d"
}

### Delete inList
DELETE http://localhost:1234/users/inList HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzOGUyMTk0YzU0NTQwYmJiYWVkMmEzNiIsImVtYWlsIjoiZmdoamtAbWFpbC5ydSIsImlhdCI6MTY3MDM5NzY3OCwiZXhwIjoxNjcwNTcwNDc4fQ.J1hLxWoIYxY99II_mT83Sey_5rDqS_h_casxZG8FlF0
Content-Type: application/json

{
  "movieId": "638bf2dd1fcdd20e4ec96b7d"
}

### Create movie
POST http://localhost:1234/movies/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzOGUyMTk0YzU0NTQwYmJiYWVkMmEzNiIsImVtYWlsIjoiZmdoamtAbWFpbC5ydSIsImlhdCI6MTY3MDM5Mjk3MywiZXhwIjoxNjcwNTY1NzczfQ.gLuNQNi6g710BwIPhbS8XYrQMQQ3gfSqkZJBvFF_GRs
Content-Type: application/json

{
  "name": "testNadfgfghjkme1s",
  "description": "test description for film1",
  "genre": [
    "scifi",
    "comedy"
  ],
  "releaseYear": 2012,
  "preview": "test-preview1.mp4",
  "video": "test1.mp4",
  "actors": [
    "Тест Актер11",
    "Тест Актер21"
  ],
  "producer": "Тест Продюссер1",
  "duration": 137,
  "poster": "test-poster1.jpg",
  "isPromo": true,
  "backgroundImage": "test-background1.jpg",
  "backgroundColor": "#FFFFFA"
}

### Get movie
GET http://localhost:1234/movies/638dfd14756f59c67761ff33 HTTP/1.1

### Update movie
PATCH http://localhost:1234/movies/6390422f53023534d11ea9e4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzOGUyMTk0YzU0NTQwYmJiYWVkMmEzNiIsImVtYWlsIjoiZmdoamtAbWFpbC5ydSIsImlhdCI6MTY3MDM5Mjk3MywiZXhwIjoxNjcwNTY1NzczfQ.gLuNQNi6g710BwIPhbS8XYrQMQQ3gfSqkZJBvFF_GRs
Content-Type: application/json

{
  "name": "NoNoNoNo"
}

### Delete movie
DELETE http://localhost:1234/movies/6390422f53023534d11ea9e4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzOGUyMTk0YzU0NTQwYmJiYWVkMmEzNiIsImVtYWlsIjoiZmdoamtAbWFpbC5ydSIsImlhdCI6MTY3MDM5Mjk3MywiZXhwIjoxNjcwNTY1NzczfQ.gLuNQNi6g710BwIPhbS8XYrQMQQ3gfSqkZJBvFF_GRs

### Get movies
GET http://localhost:1234/movies?genre=comedy&limit=1 HTTP/1.1

### Get promo
GET http://localhost:1234/movies/promo HTTP/1.1

### Get comments
GET http://localhost:1234/movies/638dfd14756f59c67761ff33/comments HTTP/1.1

### Add comment
POST http://localhost:1234/comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYzOGUyMTk0YzU0NTQwYmJiYWVkMmEzNiIsImVtYWlsIjoiZmdoamtAbWFpbC5ydSIsImlhdCI6MTY3MDM5Mjk3MywiZXhwIjoxNjcwNTY1NzczfQ.gLuNQNi6g710BwIPhbS8XYrQMQQ3gfSqkZJBvFF_GRs
Content-Type: application/json

{
  "text": "LolLol",
  "rating": 9,
  "movieId": "638dfd14756f59c67761ff33"
}
